doctool/doctool/urls.py
from django.contrib import admin
from django.urls import path
from trim import urls as trims

urlpatterns = [
    path('admin/', admin.site.urls),
] + trims.include(
    'project',
    )

doctool/project/urls.py
from django.contrib import admin
from django.urls import path
from trim import urls as trims

from . import views

urlpatterns = [

]

urlpatterns += trims.paths_dict(views, {
        'GenericFileView':('file', 'view/file/<str:pk>/'),
        'GenericDirView':('dir', 'view/dir/<str:pk>/'),
        'ProjectListView': ('project-list', ''),
        'ProjectDetailView': ('project-detail', 'project/<str:pk>/'),
    },
    safe_prefix=False
)

doctool/project/models/base.py
"""The base product models "File" and "Directory" serve as the _middle step_
when processing all the precached files. These represent the current state of
all files, connected to the (pre) project, built from the PreCacheFile

+ File and Directory models represent _markers_ or pointers to produce an output
  file.
+ They may be created by pre file dicovery, or programmatically

"""
from django.db import models
from trim import models as t_models
from django.db import models
from pathlib import Path
import os


class File(models.Model):
    project = t_models.fk('project.Project')
    rel_path = t_models.chars(max_length=3000,
        help_text='a posix path without the filename, relative to the root')
    rel_fullpath = t_models.chars(max_length=3000,
            help_text='the original path, relative to the project root')
    filename  = t_models.chars(max_length=3000,
                            help_text='the filename with the suffix')
    stem  = t_models.chars(max_length=3000,
                            help_text='the filename without the suffix')
    ext  = t_models.chars(max_length=3000,
                            help_text='The extension without the period')
    bulk_key = t_models.str_uuid()
    created, updated = t_models.dt_cu_pair()

    # encoding = 'utf-8'

    def read_text(self, encoding=None):
        a = Path(self.project.absolute_dir)
        c = a / self.rel_fullpath
        return c.read_text(encoding)# or self.encoding)

    def __str__(self):
        return f"{self.__class__.__name__}({self.id}) {self.rel_fullpath}"

    def get_kv(self, key=None):
        r = self.filekeyvalue_set.all().values('key', 'value')
        if key is not None:
            r = r.filter(key=key)
        return r


class Directory(models.Model):

    project = t_models.fk('project.Project')
    bulk_key = t_models.str_uuid()
    rel_fullpath = t_models.chars(max_length=3000,
            help_text='the original path, relative to the project root')
    parent = t_models.fk_self(related_name='upper')
    dirs = t_models.m2m_self(symmetrical=False)
    files = t_models.m2m(File)

    created, updated = t_models.dt_cu_pair()

    def __str__(self):
        return f"{self.__class__.__name__}({self.id}) {self.rel_fullpath}"


class FileKeyValue(models.Model):

    file = t_models.fk(File)
    key = t_models.chars(max_length=3000, nil=True)
    value = t_models.json()
    created, updated = t_models.dt_cu_pair()

    def __str__(self):
        return f"{self.__class__.__name__}({self.id}) {self.file} {self.key}"

doctool/project/models/out.py
"""Out models represent the _last step_ in the processing of all content.
These models contain the finalised content to write, knowing the tool has processed
the File and Directory models into FileOutput and OutputDirectory types.

The output pages and files are these output models. And when presenting should
be a finished (parsed) version of all File types.

+ Output models represent _to be written_ given File models.
+ They can be altered before write
+ Other FileOutputs and OutputDirectory models use these to process associates
"""
from django.db import models
from trim import models as t_models
from django.db import models
from pathlib import Path
import os

from .. import processors as proj_processors

UNDEFINED = {}


class FileOutput(models.Model):
    """An association of the sim data for rendering; This information may
    be edited by any process and is generated during the analyze phase.
    """
    project = t_models.fk('project.Project', nil=True)
    file = t_models.o2o('project.File', nil=True)
    rel_path = t_models.chars(max_length=3000)
    filename  = t_models.chars(max_length=3000)
    menu_label = t_models.chars(max_length=200)
    ext  = t_models.chars(max_length=3000)

    auto_build = t_models.boolean_false(help_text='Flag true to convert during parsing.')
    sim_file = t_models.boolean_false()

    bulk_key = t_models.str_uuid()
    created, updated = t_models.dt_cu_pair()

    def __str__(self):
        ext = self.ext or '*'
        return (f"{self.__class__.__name__}({self.id})"
                f"{self.rel_path}/{self.filename}.{ext}")

    def label(self):
        """Return a string for the menu label. This may be a friendly name or
        the filename.
        """
        return self.menu_label or self.filename

    def is_labeled(self):
        return self.menu_label is not None

    is_labelled = is_labeled

    def get_destination_fullpath(self, output_dir='.'):
        ss = Path(output_dir) / self.rel_path / self.filename
        return ss.with_suffix(f".{self.ext}")

    @property
    def siblings(self):
        return self.children.exclude(pk=self.pk)

    @property
    def children(self):
        d = self.directory
        if d:
            return self.directory.files.all()
        return self.outputdirectory_set.none()

    @property
    def directory(self):
        r = self.outputdirectory_set.last()
        return r

    def raw_content(self, encoding=None):

        if self.file:
            return self.file.read_text(encoding)
        if self.sim_file:
            return "Sim file (no real file)"

    def rendered_content(self, encoding=None):
        return proj_processors.render_live_model(self, encoding)

    def get_kv(self, key=None, default=UNDEFINED):
        r = self.file.get_kv(key)
        if default is UNDEFINED:
            return r
        if r.count() == 0:
            return default
        return r.get()['value']

    def kv_set(self):
        return self.file.get_kv()



class OutputDirectory(models.Model):
    """A set of directories for the output files - generated after the
    meta data has arranged the FileOutputs.
    """
    project = t_models.fk('project.Project', nil=True)
    stem = t_models.chars(max_length=300,)
    rel_path = t_models.chars(max_length=3000,
            help_text='the original path, relative to the project root')
    # parent = t_models.fk_self(related_name='upper')
    dirs = t_models.m2m_self(symmetrical=False)
    files = t_models.m2m(FileOutput)
    bulk_key = t_models.str_uuid()
    created, updated = t_models.dt_cu_pair()

    def get_parent(self):
        """Given the internal path, step_up into the relpath parent and
        return an object.
        """
        rel_path = str(Path(self.rel_path).parent.as_posix())
        ps = self.__class__.objects.filter(
                bulk_key=self.bulk_key,
                rel_path=rel_path
            )
        try:
            return ps.get()
        except self.__class__.DoesNotExist:
            return None

    @property
    def directory(self):
        return self.outputdirectory_set.last()

    def label(self):
        return self.stem or self.rel_path

    def __str__(self):
        return f"{self.__class__.__name__}({self.id}) {self.rel_path}"


doctool/project/models/pre.py
"""Pre models act as representation for the _first_ step in processing the files.
Upon a scan of a target directory, the tool creates a project and discovers
all files within.

The PreCacheFile and assets are processed into File, Directory, then into
output models.

+ PreCacheFile files represent the _real_ dataset, without alteration

"""
from django.db import models
from trim import models as t_models
from django.db import models
from pathlib import Path
import os


class Project(models.Model):

    unique_name = t_models.chars(max_length=3000, nil=True)
    given_path = t_models.chars(max_length=3000)
    absolute_dir = t_models.chars(max_length=3000)
    parent = t_models.self_fk(nil=True)
    created, updated = t_models.dt_cu_pair()

    # _short_string = '"{self.name}" x{self.count}'
    def get_output_dir(self):

        rel_path = self.get_key('output_dir')
        if rel_path:
            rel_path = rel_path.value
        else:
            print('  No output_dir path for', self)
            return None
        # Resolve to absolute
        p = Path(rel_path)
        if p.is_absolute():
            return p
        p = Path(self.absolute_dir) / p
        # normalise
        p = Path(os.path.normpath(p))
        return p

    def get_keys(self, key):
        return self.precachekeyvalue_set.filter(key=key)

    def get_key(self, key):
        keys = self.get_keys(key)
        if keys.count() == 1:
            return keys.get()
        try:
            return keys.latest('updated')
        except PreCacheKeyValue.DoesNotExist:
            return None

    def __str__(self):
        return f'{self.__class__.__name__}({self.id}) {self.unique_name}'



class PreCacheKeyValue(models.Model):

    project = t_models.fk(Project)
    key = t_models.chars(max_length=3000, nil=True)
    value = t_models.json()
    created, updated = t_models.dt_cu_pair()

    def __str__(self):
        return f'{self.key}, {self.value}'


class PreCacheFile(models.Model):
    project = t_models.fk(Project)
    bulk_key = t_models.str_uuid()
    is_file = t_models.boolean_false()
    is_used = t_models.boolean_false()
    fullpath = t_models.chars(max_length=3000, help_text='the original path')
    rel_fullpath = t_models.chars(max_length=3000,
            help_text='the original path, relative to the project root')
    path = t_models.chars(max_length=3000,help_text='a posix path without the filename')
    rel_path = t_models.chars(max_length=3000,
        help_text='a posix path without the filename, relative to the root')
    anchor = t_models.chars(help_text='the original drive')
    filename  = t_models.chars(max_length=3000,
                            help_text='the filename with the suffix')
    stem  = t_models.chars(max_length=3000,
                            help_text='the filename without the suffix')
    suffix  = t_models.chars(max_length=3000,
                            help_text='The extension including the period')
    ext  = t_models.chars(max_length=3000,
                            help_text='The extension without the period')

    created, updated = t_models.dt_cu_pair()

    def read_text(self):
        return Path(self.fullpath).read_text()


doctool/project/views.py
from django.shortcuts import render
from trim import views as trims

from . import models
from django.template.response import TemplateResponse
from django.template.base import Template


class MarkdownTemplateRenderer(TemplateResponse):
    """The standard Markdown template renderer allows the _early_ injection
    of processed markdown, to allow the standard django rendering on the given
    HTML.

    Within the primary template, apply the custom template tag.
    """
    tag = "[[MARKDOWN::RENDER]]"

    def get_tagger(self):
        word = 'MARKDOWN'
        s = "[%s]{2}%s::([A-Za-z0-9]+)[%s]{2}" % ('[', word, ']')
        print('  Looking at', s)
        return re.compile(s, re.IGNORECASE)

    @property
    def rendered_content(self):
        """Return the freshly rendered content for the template and context
        described by the TemplateResponse.

        This *does not* set the final content of the response. To set the
        response content, you must either call render(), or set the
        content explicitly using the value of this property.
        """

        # django.template.backends.django.Template
        template = self.resolve_template(self.template_name)
        context = self.resolve_context(self.context_data)
        source = self.update_template(template, context)
        old_inner = template.template
        inner = Template(source, old_inner.origin, old_inner.name, old_inner.engine)
        template.template = inner
        return template.render(context, self._request)

    def update_template(self,template, context):
        """Given the standard django template, alter the 'source' of the template
        (the outbound HTML) and early replace all markdown components before
        the django rendering.

        Ensuring this occurs before the main rendering allows the use of
        django templates within markdown.
        """
        # django.template.backends.django.Template
        old_inner = template.template
        # django.template.base.Template
        source = old_inner.source#.replace(self.tag, content or "")
        tagger = self.get_tagger()

        fmap = {
            'render': self._render_content,
            'toc': self._render_toc,
        }

        for match in tagger.finditer(source):
            word =  match[1].lower()
            print('  match', word, match)
            func = fmap.get(word, context)
            if func is None:
                print('  No rendering tool for', word)
                continue
            source = func(match, source, context)
        return source

    def _render_toc(self, match, source, context):
        """Collect the TOC from the existing markdown_unit within the model,
        and replace the match group.
        """
        span = match.group()
        replacement = context['object'].markdown_unit.toc
        return source.replace(span, replacement)

    def _render_content(self, match, source, context):
        """Replace the match group() location with the correct markdown content.
        This may also generate the markdown_unit within the model.
        """
        content = context['object'].rendered_content('utf-8')
        span = match.group()
        return source.replace(span, content)
        # return source.replace(self.tag, content or "")

import re

class GenericFileView(trims.DetailView):
    """Present a Generic file using the standard model detailview with an
    extended response_class for replacing the incoming markdown.
    """
    model = models.FileOutput
    response_class = MarkdownTemplateRenderer


class GenericDirView(trims.DetailView):
    model = models.OutputDirectory

# trims.crud(models.Project, __name__)

class ProjectListView(trims.ListView):
    model = models.Project


class ProjectDetailView(trims.DetailView):
    model = models.Project


doctool/project/templates/project/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        body {
            background: #040404fa;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ object }}</title>
</head>
<body>
    {% block body %}{% endblock body %}
</body>
</html>

doctool/project/templates/project/extras.html

<div class="extras">

    <ul>
        <li>
            <div>project</div>
            <div><a href='{% url "project-detail" object.project.id %}'>{{ object.project }}</a></div>
        </li>
        <li>
            {% if object.directory %}
                <div>directory</div>
                <div><a href='{% url "dir" object.directory.id %}'>{{ object.directory }}</a></div>
            {% else %}
                No Directory
            {% endif %}
        </li>
    </ul>

    <ul>
        <li>
            <div>object</div>
            <div>{{ object }}</div>
        </li>
        <li>
            <div>original file</div>
            <div>{{ object.file }}</div>
        </li>
        <li>
            <div>Sim File</div>
            <div>{{ object.sim_file }}</div>
        </li>
        <li>
            <div>auto build</div>
            <div>{{ object.auto_build }}</div>
        </li>
    </ul>
</div>

doctool/project/templates/project/fileoutput_base.html
{% extends "project/base.html" %}

{% block body %}
    <!-- <h2>File {{ object.filename }}</h2> -->

    {% block content %}{% endblock content %}

{% endblock body %}

doctool/project/templates/project/fileoutput_detail.html
{% extends "project/fileoutput_base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;1,400;1,489&display=swap" rel="stylesheet">

    <div class="floaty-top">

        <div class="spacer"></div>
        <a href="#" class="button no-background large" onclick='toggleView("edit", "edit-mode")'>
            <i>edit_note</i>
        </a>
    </div>
    <div class="center-content toggleview-edit">
        <div class="pad left stuck-menu">
            <div class="block-pad"></div>
            {% include "project/siblings-menu.html" %}
        </div>

        <div class="text-area">

            <div class="rendered">
                [[MARKDOWN::RENDER]]
            </div>

            <div class="raw-content">
                <div class="edit-buttons buttons">
                    <a href="#" class="button cancel secondary">Cancel</a>
                    <div class="spacer"></div>
                    <a href="#" class="button write important">Write</a>
                    <a href="#" class="button save">Save</a>
                </div>
                <pre contenteditable="true">
                    {{ object.raw_content }}
                </pre>
            </div>
        </div>

        <div class="pad right">
            <div class="block-pad"></div>
            [[MARKDOWN::TOC]]

            {# object.markdown_unit.toc|safe #}

        </div>
    </div>

    <div class="footer-pad"></div>
    <footer>
        <div class="center-center">
            {% include "project/extras.html" %}

            <div class="meta">
                meta: {{ object.markdown_unit.Meta }}

                <div class="grid">
                {% for k in object.kv_set %}
                    <div>
                        <span>{{k.key}}</span>
                        <span>{{k.value}}</span>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>

    </footer>

    <link rel="stylesheet" href='{% static "css/fileoutput-detail.css" %}'>
    <script src='{% static "js/toc.js" %}'></script>

    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    <script src='{% static "js/mermaid-integration.js" %}'></script>
    <script src='{% static "js/fileoutput-detail.js" %}'></script>
{% endblock content %}

doctool/project/templates/project/outputdirectory_base.html
{% extends "project/base.html" %}

{% block body %}
    <h2>DIR: {{ object.rel_path }}</h2>
    <ul>
        <li>here: {{ object.rel_path }}</li>
        <li>Parent:  <a href='{% url "dir" object.directory.id %}'>{{ object.directory }}</a></li>

        <li>project:
            <a href='{% url "project-detail" object.project.id %}'>{{ object.project }}</a>
        </li>
    </ul>

    <h3>Dirs</h3>

    <ul>
        {% for dir in object.dirs.all %}
            <li>
                <a href='{% url "dir" dir.id %}'>{{ dir }}</a>
            </li>
        {% endfor %}
    </ul>

    <h3>Files</h3>
    <ul>
        {% for file in object.files.all %}
            <li>
                <a href='{% url "file" file.id %}'>{{ file }}</a>
            </li>
        {% endfor %}
    </ul>

    {% block content %}

    {% endblock content %}

{% endblock body %}

doctool/project/templates/project/outputdirectory_detail.html
{% extends "project/outputdirectory_base.html" %}
{% load static %}

{% block content %}
    <p>This is a directory page. The content seen here is for the _folder_ {{ object }}</p>
    <link rel="stylesheet" href='{% static "css/fileoutput-detail.css" %}'>
{% endblock content %}

doctool/project/templates/project/project_detail.html
{% extends "project/base.html" %}
{% load static %}

{% block body %}
    <h2>Project {{ object.unique_name }}</h2>

    <ul>
        <li>
            <a href='{% url "project-list" %}'>Project List</a>
        </li>
        {% if object.parent %}
            <li>parent:
                <a href='{% url "project-detail" object.parent.id %}'>{{ object.parent }}</a>
            </li>
        {% endif %}

    </ul>

    <h3>Directories</h3>
    <ul>
        {% for dir in object.outputdirectory_set.all %}
            <li>
                <a href='{% url "dir" dir.id %}'>{{ dir }}</a>
            </li>
        {% endfor %}
    </ul>

    <h3>Files</h3>
    <ul>
        {% for file in object.fileoutput_set.all %}
            <li>
                <a href='{% url "file" file.id %}'>{{ file }}</a>
            </li>
        {% endfor %}
    </ul>

    {% block content %}{% endblock content %}
    <link rel="stylesheet" href='{% static "css/fileoutput-detail.css" %}'>

{% endblock body %}

doctool/project/templates/project/project_list.html
{% load static %}
<ul>
    {% for pr in object_list %}
    <li>
        <a href="{% url 'project-detail' pr.id %}">{{ pr }}</a>
    </li>
    {% endfor %}
    <link rel="stylesheet" href='{% static "css/fileoutput-detail.css" %}'>
</ul>

doctool/project/templates/project/siblings-menu.html
<div class="sibling-menu">
    {% with parent=object.directory.directory %}
    <div class="parent-dir">
        {% if parent != object.directory %}
        <a href='{% url "dir" parent.id %}'>{{ parent.label }}</a>
        <span class="dir-sep">/</span>
        {% endif %}
        <a href='{% url "dir" object.directory.id %}'>{{ object.directory.label }}/</a>
    </div>
    {% endwith %}
    <ul>
        {% if object.children %}
            {% for file in object.children.all %}

                <li class='{% if file.is_labelled is False %}no-label{% endif %} {% if file.id == object.id %}selected{% endif %}'>
                    <a href='{% url "file" file.id %}'>
                        <span class="text">{{ file.label }}</span>
                    </a>
                </li>
            {% endfor %}
        {% else %}
            <li>No Siblings</li>
        {% endif %}
    </ul>
</div>